version: '3.2'

services: 
  port: 
    env_file:
      - services/port/.env
      - .env
    build: 
      dockerfile: services/port/Dockerfile
      context: .
    environment: 
      - RUST_LOG=debug
    network_mode: host
  matching-engine:
    environment: 
      - RUST_LOG=debug
    env_file: 
      - services/matching-engine/.env
      - .env
    network_mode: host
    build: 
      context: .
      dockerfile: services/matching-engine/Dockerfile

