version: '3.2'

services: 
  # gateway: 
  #   env_file:
  #     - services/gateway/.env
  #     - .env
  #   build: 
  #     dockerfile: services/gateway/Dockerfile
  #     context: .
  #   network_mode: host
  matching-engine:
    env_file: 
      - .env
    network_mode: host
    build: 
      context: .
      dockerfile: services/matching-engine/Dockerfile

