version: '3.2'

services: 
  port: 
    env_file:
      - services/port/.env
      - .env
    build: 
      dockerfile: services/port/Dockerfile
      context: .
    networks: 
      - backend
    ports: 
      - 8080:8080
    environment: 
      - RUST_LOG=debug
  matching-engine:
    networks: 
      - backend
    environment: 
      - RUST_LOG=debug
    env_file: 
      - services/matching-engine/.env
      - .env
    build: 
      context: .
      dockerfile: services/matching-engine/Dockerfile


networks: 
  backend:
