version: '3.2'

services: 
  gateway: 
    env_file:
      - services/gateway/.env
      - .env
    build: 
      context: services/gateway
    network_mode: host
  matching-engine:
    env_file: 
      - .env
    network_mode: host
    build: 
      context: services/matching-engine

