version: '3.2'


services: 
  gateway: 
    env_file: services/gateway/.env
    build: 
      context: services/gateway
    ports: 
      - '8080:8080'
  matching-engine:
    build: 
      context: services/matching-engine
