[package]
name = "fixer-upper"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.123", features=["derive"]}
serde_with = "1.6.4"
chrono = {version = "0.4.19", features = ["serde"]}
