[package]
name = "matching-engine"
version = "0.1.0"
authors = ["Will Johnston <wbjohnston@gmail.com>"]
edition = "2018"
publish = false


[lib]
name = "matching_engine"
src = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matchbook-types = { git = "https://github.com/wbjohnston/matchbook" }
